### ISSUE TITLE
内联样式有错误

### ISSUE THREAD

**Issue by sexyHuang** [icindy/wxParse#10]
`element.style {
color:,#808000;
`}``

参数前莫名多出了‘，’

**Comment by icindy** [comment]
好的 谢谢反馈 我看下

**Comment by richardqiaodaxia** [comment]
将html2json.js 中的约88行到91行的代码注释掉就好了
            if (value.match(/ /)) {
               value = value.split(' ');
             }

**Comment by icindy** [comment]
#21
