### ISSUE TITLE
很多公众号文章中的iframe视频，无法解析！！

### ISSUE THREAD

**Issue by willxi** [icindy/wxParse#121]
<iframe class="video_iframe" allowfullscreen="" scrolling="no" data-vidtype="-1" width="670" height="502.5" frameborder="0" src="http://v.qq.com/iframe/player.html?vid=s0151oiypl5&amp;width=670&amp;height=502.5&amp;auto=0" style="width: 670px !important; height: 502.5px !important; overflow: hidden;"></iframe>
视频 无法解析，有的时候 src为 data-src

**Comment by icindy** [comment]
不支持iframe的解析

**Comment by dog69** [comment]
怎样做到iframe解析？或者实现的替代方案？

**Comment by fernandoxu** [comment]
解决了吗？
