### ISSUE TITLE
多数据循环的时候，列表key必须是数字吗？

### ISSUE THREAD

**Issue by baiyuxiong** [icindy/wxParse#133]
replyArr['A'] = '回复1';
replyArr['B'] = '回复2';

for (var k in replyArr) {
              WxParse.wxParse('option' + k, 'html', replyArr[k], that);
              if (k === data.options.length - 1) {
                WxParse.wxParseTemArray("options", 'option', data.options.length, that)
              }
            }

**Comment by icindy** [comment]
代码部分你可以自己进行自定义

key理论上是可以定制的
