### ISSUE TITLE
有推荐使用的编辑器嘛！

### ISSUE THREAD

**Issue by shengke90** [icindy/wxParse#137]
您好！如题，在手机端有推荐富文本编辑器嘛！

**Comment by TheSixth** [comment]
VS code 不错

**Comment by icindy** [comment]
@shengke90 你的意思是微信小程序版的富文本编辑器吧

**Comment by shengke90** [comment]
@icindy 是的呢！最近项目要在小程序里做论坛发帖功能

**Comment by icindy** [comment]
@shengke90 

目前没有，但是在构思，如果写好了再通知你吧
