### ISSUE TITLE
换了V2, that.setData 报错

### ISSUE THREAD

**Issue by leke2015** [icindy/wxParse#138]
之前用的都好好的，今天看见有v2, 就覆盖了
结果报错了

> that.setData is not a function;at pages/about/about fetchData function;at api request success 
> callback function
>TypeError: that.setData is not a function

> that.setData is not a function;at pages/detail/detail fetchDetailData function;at api request 
> success callback function
>TypeError: that.setData is not a function

**Comment by icindy** [comment]
你是说使用了v0.2？

如果是 建议选择0.3

**Comment by leke2015** [comment]
谢谢您，换了0.3问题解决了

**Comment by icindy** [comment]
不客气 解决了就好 

使用中遇到任何问题 欢迎PR
