### ISSUE TITLE
音频没有被解析过来

### ISSUE THREAD

**Issue by baikatian** [icindy/wxParse#146]
html中有audio标签，经过wxParse的解析后直接被过滤掉了，<viewclass="wxParse-audio"></view>里面为空，我还没来得及看源码是怎么处理的

**Comment by baikatian** [comment]
解决：在插件的wxParse.wxml中没有audio的模板，查找一个video的，复制一个修改即可，记得加上 controls="true"，否则前端显示尺寸为0

**Comment by WizardWang94** [comment]
@baikatian 你好，我也在wxParse.wxml中加了audio的模板，前端可以解析出来，音源没有问题，但是音频不能播放，你有遇到相同的问题吗？

**Comment by huhai0403** [comment]
> @baikatian 你好，我也在wxParse.wxml中加了audio的模板，前端可以解析出来，音源没有问题，但是音频不能播放，你有遇到相同的问题吗？
你好，我也遇见这个问题，富文本中的音频在ios下无法播放，请问你解决了吗？
