### ISSUE TITLE
如何渲染一个列表

### ISSUE THREAD

**Issue by sunny-baiye** [icindy/wxParse#149]
一个数据列表中的某个值是富文本，如何配合微信的列表渲染使用wxParse呢

**Comment by icindy** [comment]
https://github.com/icindy/wxParse/wiki/wxParse%E5%A4%9A%E6%95%B0%E6%8D%AE%E5%BE%AA%E7%8E%AF%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
