### ISSUE TITLE
图片默认为屏幕宽度，外层view加padding后显示向右偏离

### ISSUE THREAD

**Issue by Choicelin** [icindy/wxParse#167]
您好，如题

**Comment by ximolang** [comment]
倒不如强制设wxss图片宽度100%适应

**Comment by huangdou0204** [comment]
可以使用 多加一层view，在内层view上 使用class 样式， 使用margin 来替换padding的效果即可解决！
自己研究试验后完美！ @Choicelin

**Comment by jfjbYXY** [comment]
@huangdou0204 不行啊，大兄弟，我试了

**Comment by chesterchenn** [comment]
@jfjbYXY 
/**
* WxParse.wxParse(bindName , type, data, target,imagePadding)
* 1.bindName绑定的数据名(必填)
* 2.type可以为html或者md(必填)
* 3.data为传入的具体数据(必填)
* 4.target为Page对象,一般为this(必填)
* 5.imagePadding为当图片自适应是左右的单一padding(默认为0,可选)
*/
参考第五个参数
