### ISSUE TITLE
我在努力的帮你找到关于模板的递归和互相嵌套的问题。

### ISSUE THREAD

**Issue by lynk-coder** [icindy/wxParse#18]
我对你的项目重新进行了整改，精简掉了很多不必要的文件。
微信小程序现在属于公测阶段，模板的作用域是独立的，他对于模板递归和互相嵌套的问题估计是故意屏蔽，不让开发者去无意间制造死循环，但是忽略掉了非递归和循环的问题。
我也在努力帮你解决这个问题，解决后我会给你发个方案。

**Comment by icindy** [comment]
非常感谢您的帮助

如果方便可以进行Pull request操作，或者联系我的个人微信cindycoder

期待与你一起交流

再次感谢
