### ISSUE TITLE
图片加载完成时突然抖动

### ISSUE THREAD

**Issue by sunlei4076** [icindy/wxParse#185]
如图：
![wechatsight11](https://user-images.githubusercontent.com/13211268/33697861-12e8a2b8-db44-11e7-8619-a7f64ab3a4ed.gif)

代码：
![wxml](https://user-images.githubusercontent.com/13211268/33697928-64f312dc-db44-11e7-99d3-995ccf0cc9c2.png)
![wxss](https://user-images.githubusercontent.com/13211268/33697930-66674462-db44-11e7-8b0a-15943b32b05c.png)

**Comment by sunlei4076** [comment]
富文本字符串：
"<p><img alt=\"\" height=\"154\" src=\"http://edutest3.zejicert.cn/files/course/2017/12-06/1704000274f7878097.jpg?7.3.40\" width=\"273\" /></p>\r\n\r\n<p><img alt=\"\" src=\"http://edutest3.zejicert.cn/files/course/2017/12-06/1705211ae83a418166.jpg?7.3.40\" /></p>\r\n"

**Comment by sunlei4076** [comment]
已解决
![fixedimg](https://user-images.githubusercontent.com/13211268/33700497-a5425626-db54-11e7-91db-d5c3a16aa7fc.png)

**Comment by MrReN** [comment]
谢谢，试试看。我也遇到了这个问题
