### ISSUE TITLE
style问题

### ISSUE THREAD

**Issue by foooy** [icindy/wxParse#21]
{
    "id": 3801,
    "title": "服务活动",
    "author": "admin",
    "content": "<p style=\"text-align: center; text-indent: 0;\"><img alt=\"IMG_0050\" border=\"0\" src=\"https://static.oschina.net/uploads/space/2016/1125/094951_MLjx_2340783.png\"></p>\n<p> </p>\n<p>服务活动</p>\n"
    "status": 1,
    "image": "",
    "order": 0,
    "url": "http://www.baidu.com",
    "time": 1479527100
}

这样的style会有问题

**Comment by icindy** [comment]
谢谢 反馈 我会在0.3版本进行修复这些问题

**Comment by icindy** [comment]
新版本发布，0.3 请尝试，如有问题请提交issue
