### ISSUE TITLE
android高版本不能解析

### ISSUE THREAD

**Issue by linjian99666** [icindy/wxParse#216]
机型：vivo x9i
android版本：7.1.2
vivo ROM:Funtouch OS_3.1
微信版本：6.6.5
问题描述：以前低版本系统是没问题的，可以正常解析，但是我升级了高版本之后，不能解析了，富文本出不来

**Comment by incasedo** [comment]
注释掉html2json.js中的console.dir(value);
我也遇到这个问题, 跟踪了一下, 注释掉后, 解决了.

**Comment by linjian99666** [comment]
@incasedo  非常感谢，确实是这样，注释掉两个console.dir(value)；之后就没有问题了。
