### ISSUE TITLE
markdown解析的问题

### ISSUE THREAD

**Issue by yangbo5207** [icindy/wxParse#22]
我想用测试一下，因此写了下面这句
```js
WxParse.wxParse('md', '## this is h2.',self)
```
但是解析结果2个井号还在，并没有解析
![image](https://cloud.githubusercontent.com/assets/13758605/20658710/da72f06e-b579-11e6-895a-ce630d1a2e72.png)

**Comment by icindy** [comment]
谢谢 反馈 我会在0.3版本进行修复这些问题

**Comment by icindy** [comment]
你好，确实是存在这个问题，但是在实际生产环境下可以使用。

我目前没有找到良好的解决方案。

你可以尝试0.3新版

**Comment by yangbo5207** [comment]
@icindy 嗯，好的
