### ISSUE TITLE
关于图片尺寸

### ISSUE THREAD

**Issue by haosblog** [icindy/wxParse#25]
听说作者大大在开发下一个版本，我就不提PR了，提个小建议吧。

图片自适应是以屏幕宽度为标准的，但是如果页面存在边距，会容纳不下图片导致图片显示不全。暂时我自己的解决方案是wxParseImgLoad方法新增一个padding参数，WxParse.js的wxAutoImageCal方法中利用padding和windowWidth计算出图片宽度的上限

**Comment by icindy** [comment]
谢谢反馈 也欢迎pr一下 我可以在下一版本中做参考，哈哈

我正在开发0.3版本 同师也正在收集上一版本大家的建议和意见。

感谢你的支持，你的修改意见很重要。

**Comment by icindy** [comment]
新增imagePadding可选配置
```
function wxParse(bindName = 'wxParseData', type='html', data='<div class="color:red;">数据不能为空</div>', target,imagePadding)
```
