### ISSUE TITLE
strong标签无法解析

### ISSUE THREAD

**Issue by myworldhere** [icindy/wxParse#252]
![wechatimg71](https://user-images.githubusercontent.com/15796874/41590240-20d0fd6a-73e9-11e8-8d63-3aabf7e5e7c0.jpeg)
解析出来的结果是
![wechatimg70](https://user-images.githubusercontent.com/15796874/41590134-dc3bf54c-73e8-11e8-8b18-dcb5053fe0f6.jpeg)
strong标签无法解析，求大神支招！

**Comment by myworldhere** [comment]
解析完后没加粗，却换行了。。。

**Comment by lettgers** [comment]
在模板里面自定义扩展一下不行吗?

**Comment by VipMinF** [comment]
请问这个问题解决了嘛？ 好想最近才出现的，以前不会的

**Comment by myworldhere** [comment]
@lettgers 怎么处理？请教

**Comment by myworldhere** [comment]
仔细看了一下代码。发现是因为没有导入wxParse.wxss，只要在app.wxss中导入库里的wxParse.wxss就能解决问题。

**Comment by Jayxiang** [comment]
> 仔细看了一下代码。发现是因为没有导入wxParse.wxss，只要在app.wxss中导入库里的wxParse.wxss就能解决问题。

确实是。
