### ISSUE TITLE
解析层级出不对

### ISSUE THREAD

**Issue by shumingjian** [icindy/wxParse#284]
<s pan style="color: rgb(255, 0, 0);">
    <b style="">
      <div style="text-align: center;">
        <b>预收200元定金</b>
      </div>
    </b>
    <b style="">
      <div style="text-align: center;">
        <b style="">余额返程路上结算清帐</b>
      </div>
    </b>
  </s pan>

下面是解析出来的
<view class="wxParse-span wxParse-inline"style="color: rgb(255, 0, 0);">
    <view class="wxParse-b wxParse-inline"style=""></view>
</view>
<view class="wxParse-div"style="text-align: center;">
    <view class="wxParse-b wxParse-inline">
       <view class="WxEmojiView wxParse-inline">预收200元定金</view>
    </view>
</view>
<view class="wxParse-b wxParse-inline"style=""></view>
<view class="wxParse-div"style="text-align: center;">
    <view class="wxParse-b wxParse-inline"style="">
          <view class="WxEmojiView wxParse-inline">余额返程路上结算清帐</view>
    </view>
</view>

wxParse-span所在的view  没有包裹下面两个view
我的html代码里span标签应该包裹下面两个子view  但是实际解析出来的是同一层级

**Comment by leenty** [comment]
所以这个是怎么解决了？@shumingjian
