### ISSUE TITLE
调试信息可选

### ISSUE THREAD

**Issue by levy9527** [icindy/wxParse#328]
开发的时候，控制台wxParse会输出console.log信息，当我需要查看别的console.log信息时，被wxParse的调试信息干扰到了，希望使用者能控制是否输出调试信息。

另外，我不清楚生产环境wxParse是否也会打印console.log，对小程序以及wxParse不是很熟悉。

**Comment by ianzhi** [comment]
[仓库地址](https://github.com/ianzhi/wxParse)
已经删除调试信息

**Comment by levy9527** [comment]
ok
