### ISSUE TITLE
烂尾楼了？

### ISSUE THREAD

**Issue by bosscheng** [icindy/wxParse#330]
烂尾楼了？

**Comment by ianzhi** [comment]
应该是不再维护了，有使用问题欢迎到https://github.com/ianzhi/wxParse提issue。

**Comment by ianzhi** [comment]
不算烂尾，起码是可用的。
欢迎关注[新仓库](https://github.com/ianzhi/wxParse)。

**Comment by bosscheng** [comment]
好的，谢谢
