### ISSUE TITLE
对于拼接的多图片，中间会出现一条白线，已经确认多图中没有其他html组件

### ISSUE THREAD

**Issue by getideas** [icindy/wxParse#338]
对于拼接的多图片，中间会出现一条白线，已经确认多图中没有其他html组件，只是image

**Comment by baokuanze** [comment]
最外层 font-size:0

**Comment by getideas** [comment]
> 
> 
> 最外层 font-size:0

测试了没有效果，具体是加在哪里  <view class="detail">
    <import src="/lib/wxParse/wxParse.wxml" />
    <template is="wxParse" data="{{wxParseData:goodsDetail.nodes}}" />
  </view>在detail里面吗？

**Comment by baokuanze** [comment]
page{
font-size:0
}

**Comment by getideas** [comment]
最终是修改wxParseImg中的mode="scaleToFill" 解决了这个白线条问题。
