### ISSUE TITLE
多次调用之后会导致加载速度越来越慢

### ISSUE THREAD

**Issue by ee07b570** [icindy/wxParse#34]
使用0.3的包，多次加载会导致页面渲染越来越慢。
手机测试效果延时明显，在不断返回、加载、返回、加载的过程中，会导致页面加载越来越慢，进入页面白屏时间越来越久。

**Comment by icindy** [comment]
谢谢 这应该是一个重要bug

谢谢 我去尝试并修改

**Comment by icindy** [comment]
请问一下 
你是不是渲染放在了onshow中？

**Comment by icindy** [comment]
如果不是需求要求，如每次请求显示的html都有变

如果html没有变动 可以在onLoad中使用，这样只会每次加载一次

**Comment by ee07b570** [comment]
我放到了onload中，情况也是一样的。。。似乎我调用setTimeout执行异步加载也对这个没有影响。主要问题是，为什么需要加载时间会越来越长？

**Comment by icindy** [comment]
嗯  我正在看 

这个问题确实是一个问题 
谢谢反馈

**Comment by yangbo5207** [comment]
同样发现了这个问题，持续关注中... ...

**Comment by icindy** [comment]
现在试试，我修复了一次 有问题请重开bug
