### ISSUE TITLE
富文本中含有字符“&quot;”会导致无法完成解析

### ISSUE THREAD

**Issue by luozhibo2003** [icindy/wxParse#35]

**Comment by icindy** [comment]
谢谢反馈 
请给予一段测试代码
我看下如何修改

**Comment by luozhibo2003** [comment]
`<p><span style="font-family: 微软雅黑, &quot;Microsoft YaHei&quot;;"><span style="color: rgb(51, 51, 51); font-size: 14px; text-indent: 28px; background-color: rgb(255, 255, 255);">诗人大半生居住在襄阳城南岘山附近的涧南园，该诗即创作于诗人在家乡隐居读书、写诗自娱期间。诗人求仕不遇，心情苦闷，在极不得意的时候，与几个朋友登上岘山游玩，凭吊羊公碑，想到羊祜当年的心境，想起羊祜说过的“自有宇宙，便有此山，由来贤者胜士登此远望如我与卿着，皆湮灭无闻，使人伤悲”的话，正与诗人的处境正相吻合。由此借古抒怀，写下了这首诗。</span><span style="font-size: 12px; line-height: 0; position: relative; vertical-align: baseline; top: -0.5em; margin-left: 2px; color: rgb(51, 102, 204); cursor: default; padding: 0px 2px; text-indent: 28px; background-color: rgb(255, 255, 255);">[3]</span></span><a style="color: rgb(19, 110, 194); position: relative; top: -50px; font-size: 0px; line-height: 0; font-family: arial, 宋体, sans-serif; text-indent: 28px; white-space: normal; background-color: rgb(255, 255, 255);" name="ref_[3]_383319"></a>&nbsp;</p>`

**Comment by luozhibo2003** [comment]
试试这段

**Comment by icindy** [comment]
已经修复，可以试试
