### ISSUE TITLE
如果我传入的内容中有不完整的标签模板会爆出undefined，但是我希望报错后能返回显示源数据

### ISSUE THREAD

**Issue by dongrizhixue** [icindy/wxParse#37]
今天突然发现一个问题，我传入了一个的不完整的标签"<img"结果wxparse模板空了，我希望的是，如果内部报错，请原路返回我传入的内容，而不是空字符串

**Comment by icindy** [comment]
好的 稍后我处理看一下 
谢谢反馈

**Comment by icindy** [comment]
已经修复 下载新版常识
