### ISSUE TITLE
含有<p><br></p>时只有换行高度不对

### ISSUE THREAD

**Issue by mengzhihoing** [icindy/wxParse#41]
文章中含有以上标记时只有换行，没有p的高度。希望修复，谢谢。

例如代码：
![image](https://raw.githubusercontent.com/mengzhihoing/image/master/code.png)  

小程序显示：
![image](https://raw.githubusercontent.com/mengzhihoing/image/master/wechat.png)  

正常网页显示：
![image](https://raw.githubusercontent.com/mengzhihoing/image/master/web.png)

**Comment by mengzhihoing** [comment]
同时有多个<br>br标记时也只换了一行

**Comment by icindy** [comment]
这个需要你自己去`wxDiscode.js`中自省定制替换方案

**Comment by 2753837446** [comment]
自行替换怎么来修复这个问题啊  能提供下代码吗
