### ISSUE TITLE
包含代码是会出错！

### ISSUE THREAD

**Issue by CoderJackyHuang** [icindy/wxParse#42]
HTML页面内容如下：

微信小程序如何实现分享功能？最近在做微信小程序项目，正好需要做页面分享功能！不过很幸运的是，微信小程序已经提供了专用的API功能，让我们轻轻松松实现小程序分享功能。分享函数onShareAppMessage在 Page 中定义 onShareAppMessage 函数，设置该页面的分享信息。只有定义了此事件处理函数，右上角菜单才会显示“分享”按钮 用户点击分享按钮的时候会调用 此事件需要 return 一个 Object，用于自定义分享内容 自定义分享字段字段&nbsp;&nbsp;说明&nbsp;&nbsp;默认值\r\ntitle&nbsp;&nbsp;&nbsp;分享标题&nbsp;&nbsp;&nbsp;&nbsp;当前小程序名称\r\ndesc&nbsp;&nbsp;&nbsp;&nbsp;分享描述&nbsp;&nbsp;&nbsp;&nbsp;当前小程序名称\r\npath&nbsp;&nbsp;&nbsp;&nbsp;分享路径&nbsp;&nbsp;&nbsp;&nbsp;当前页面&nbsp;path&nbsp;，必须是以&nbsp;/&nbsp;开头的完整路径调用方式onShareAppMessage:&nbsp;function&nbsp;()&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{\r\n&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;&#39;运营小帮手&#39;,\r\n&nbsp;&nbsp;&nbsp;&nbsp;desc:&nbsp;&#39;运营小帮手百科创建、修改、删除和优化，新闻发稿服务、软件开发和网站SEO优化，运营小帮手，您的好助手！&#39;,\r\n&nbsp;&nbsp;&nbsp;&nbsp;path:&nbsp;&#39;/pages/index/index&#39;\r\n&nbsp;&nbsp;&nbsp;&nbsp;}\r\n}这样就实现了我们的功能

**Comment by icindy** [comment]
应该可以解析的，你下载新版试试
