### ISSUE TITLE
解析以下一串HTML一直报错WAService.js:3 thirdScriptError

### ISSUE THREAD

**Issue by 9streets** [icindy/wxParse#43]
https://xcx.outku.com/cms/ajax.php?act=shell  粘贴不了源代码，直接贴 个地址了，解析源代码时，一直报上面错误，不知道是哪个特殊符号造成，详细错误如下：
WAService.js:3 thirdScriptError
undefined;at "pages/index/index" page lifeCycleMethod onLoad function
undefined

**Comment by zsj1029** [comment]
me too 动态根据 url get过来的html源码标签报一样的错，写死的就没问题了

**Comment by icindy** [comment]
代码如果不规范

1.比如style属性中带有style = "color:"red""这样的内联样式 会出现问题
2.标签没有闭包，也会有错误。

如果方便，最好贴一下需要解析HTML贴一下我看下

**Comment by 9streets** [comment]
` <p>1.创建如下符号链接</p> <div class="codeText"> <div class="codeHead"><span class="lantxt">C/C++ Code</span><span class="copyCodeText" style="cursor:pointer" onclick="copyIdText('code_6795')">复制内容到剪贴板</span></div> <div id="code_6795"> <ol start="1" class="dp-cpp"> <li class="alt"><span><span>sudo&nbsp;ln&nbsp;-s&nbsp;/etc/apache2/mods-available/include.load&nbsp;/etc/apache2/mods-enabled&nbsp;&nbsp;</span></span></li> </ol> </div> </div> <p>2.编辑对应的项目xxx.conf</p> <div class="codeText"> <div class="codeHead"><span class="lantxt">C/C++ Code</span><span class="copyCodeText" style="cursor:pointer" onclick="copyIdText('code_4040')">复制内容到剪贴板</span></div> <div id="code_4040"> <ol start="1" class="dp-cpp"> <li class="alt"><span><span>&lt;Directory&nbsp;/var/www/&gt;&nbsp;&nbsp;</span></span></li> <li><span>&nbsp;&nbsp;&nbsp;&nbsp;Options&nbsp;Indexes&nbsp;FollowSymLinks&nbsp;MultiViews&nbsp;<span style="color: rgb(255, 0, 0);">IncludesNOEXEC&nbsp;#增加IncludesNOEXEC</span>&nbsp;&nbsp;</span></li> <li class="alt"><span>&nbsp;&nbsp;&nbsp;&nbsp;AllowOverride&nbsp;None&nbsp;&nbsp;</span></li> <li><span>&nbsp;&nbsp;&nbsp;&nbsp;Order&nbsp;allow,deny&nbsp;&nbsp;</span></li> <li class="alt"><span>&nbsp;&nbsp;&nbsp;&nbsp;allow&nbsp;from&nbsp;all&nbsp;&nbsp;</span></li> <li><span>&nbsp;&nbsp;&nbsp;&nbsp;<span style="color: rgb(255, 0, 0);">AddOutputFilter&nbsp;INCLUDES&nbsp;.inc&nbsp;.shtml&nbsp;&nbsp;#增加你需要引用公共名的后缀&nbsp;</span>&nbsp;</span></li> <li class="alt"><span>&lt;/Directory&gt;&nbsp;&nbsp;</span></li> </ol> </div> </div> <p><br /> 3.重启apache<br /> <br /> 4.在对应目录下创建测试文件<br /> 文件内容如下：<br /> &nbsp;</p> <div class="codeText"> <div class="codeHead"><span class="lantxt">C/C++ Code</span><span class="copyCodeText" style="cursor:pointer" onclick="copyIdText('code_8434')">复制内容到剪贴板</span></div> <div id="code_8434"> <ol start="1" class="dp-cpp"> <li class="alt"><span><span>&lt;html&gt;&nbsp;&nbsp;</span></span></li> <li><span>&lt;head&gt;&nbsp;&nbsp;</span></li> <li class="alt"><span>&lt;title&gt;SSI&nbsp;Test&nbsp;Page&lt;/title&gt;&nbsp;&nbsp;&nbsp;</span></li> <li><span>&lt;/head&gt;&nbsp;&nbsp;</span></li> <li class="alt"><span>&lt;body&gt;&nbsp;&nbsp;</span></li> <li><span>&lt;!--#echo&nbsp;var=<span class="string">&quot;DATE_LOCAL&quot;</span><span>&nbsp;--&gt;&nbsp;&nbsp;</span></span></li> <li class="alt"><span>&lt;!--#include&nbsp;<span class="keyword">virtual</span><span>=</span><span class="string">&quot;xxxxx.inc&quot;</span><span>--&gt;&nbsp;&nbsp;</span></span></li> <li><span>&lt;/body&gt;&nbsp;&nbsp;</span></li> <li class="alt"><span>&lt;/html&gt;&nbsp;&nbsp;</span></li> </ol> </div> </div> <p><br /> 5、保存后在浏览器里访问：<br /> <br /> http://xxx.outku.com/test.htm<br /> <br /> 如果看到当前时间输出（ 例如：Monday, 05-Dec-2016 18:18:25 CST ）,那么apache ssi就配置成功了。<br /> &nbsp;</p> `

**Comment by icindy** [comment]
已经修改了，可以正常显示
