### ISSUE TITLE
UEditor插件编辑出来的富文本解析bug

### ISSUE THREAD

**Issue by naoatnehc** [icindy/wxParse#46]
之前写的博客的内容数据是html富文本，用这个插件，有些文章转换正常，有几篇数据异常，加载时出错
![2017-01-11 14 47 06](https://cloud.githubusercontent.com/assets/18466310/21838434/f029564a-d80c-11e6-81ac-caa3ff5e84dd.png)
数据接口 [https://zuo11.com/wechat](https://www.zuo11.com/wechat), 对js不怎么熟，你们可以找找看是什么问题。
js:
`wx.request({
      url: "https://zuo11.com/wechat", 
      data: {
        mark: 'home'
      },
      method:'POST',
      header: {
        'content-type': 'application/json'
      },
      success: function(res) {
        console.log(res.data.notes[0].noteTime),
        that.setData({
          notes_title : res.data.notes[8].noteTitle,
          notes: res.data.notes,
          note_time:res.data.notes[8].noteTime,
         })
        WxParse.wxParse('notes_content','html',res.data.notes[5].noteContent,that,10) 
      }
    })`
xml:
`<view class="detail">
      <template is="wxParse" data="{{wxParseData:notes_content.nodes}}"/>
    </view>`

**Comment by icindy** [comment]
请提供一份HTML
方便我测试

同时我已经更新了新版本，你可以测试一下是否可以解析了

**Comment by naoatnehc** [comment]
刚才试了试，发现不能解析
![2017-01-22 17 53 26](https://cloud.githubusercontent.com/assets/18466310/22181672/c4416302-e0cb-11e6-9da6-dce4c08c116b.png)
正常显示为"3.非head内<style>"，你试试看，暂时没发现其它问题，基本都能显示正常
html文本: [html.txt](https://github.com/icindy/wxParse/files/721846/html.txt)
