### ISSUE TITLE
后两个选项卡无法加载内容

### ISSUE THREAD

**Issue by FrankHan** [icindy/wxParse#5]
你好，我download了下来什么都没改动，前两个选项卡有内容，后两个都是空白哦，不知道为什么？

谢谢你如此优质的资源！

![4](https://cloud.githubusercontent.com/assets/3120844/20035067/5ee96b32-a410-11e6-98d7-82d0eff98e7f.jpg)
![2](https://cloud.githubusercontent.com/assets/3120844/20035069/5eec6a76-a410-11e6-8f26-7751a7081490.jpg)
![1](https://cloud.githubusercontent.com/assets/3120844/20035066/5ee90d5e-a410-11e6-9379-628a180068ed.jpg)
![3](https://cloud.githubusercontent.com/assets/3120844/20035068/5eeba474-a410-11e6-8416-f3118d77e1ba.jpg)

**Comment by icindy** [comment]
## 先确定一件事情
您是不是在使用了app id了？还是选择的无appid？

## 什么都没有动的话

你可以尝试使用清除一下缓存试试，清除以后可以尝试重启您的微信小程序开发工具

**Comment by icindy** [comment]
有很大影响
对于设定了app id的项目 
需要在后台设定相关域名才能进行请求哈

如果你是想要看下wxParse的效果
你可以不需要添加app id进行查看

如果实际使用时，对于你需要域名放置在配置页面的域名里面

**Comment by FrankHan** [comment]
试了，可以了，谢谢啊！我好好研究研究！

**Comment by icindy** [comment]
OK 我将关闭这个bug 周一会上version0.2

欢迎加入[http://weappdev.com/](http://weappdev.com/) 微信小程序开发论坛
扫描上面的二维码 加入微信群 可以实时交流哈

**Comment by FrankHan** [comment]
好的 谢谢！
