### ISSUE TITLE
行内样式的字符实体解析导致解析html失败

### ISSUE THREAD

**Issue by ioolllzzzz** [icindy/wxParse#50]
行内样式出现&quot; 在解析后 会变成 行内样式双层 双引号导致解析失败。比如
原html：  `<html>... <p style="font-family: &quot;宋体&quot;; font-size: 14px;">  ...</html>`
解析后html：`<html>... <p style="font-family: "宋体"; font-size: 14px;">  ...</html>`

双层双引号导致解析失败，
建议正则匹配行内样式的&quot; 替换成 与行内样式外层不同的引号

**Comment by icindy** [comment]
谢谢 

我周末更新一次
