### ISSUE TITLE
wxParse多数据循环使用时图片没法自适应

### ISSUE THREAD

**Issue by ya00la** [icindy/wxParse#51]
按照wxParse多数据循环使用方法操作后，发现图片没有自适应显示，
html的dom节点获取到的style如下
`<img src="XXX.png" style="height:px;width:px">`

**Comment by icindy** [comment]
谢谢 反馈 本周末会更新一版

目前image标签官方已经支持自适应 我会处理一版

**Comment by icindy** [comment]
已经处理，请下载新版
