### ISSUE TITLE
html注释会导致解析失败

### ISSUE THREAD

**Issue by charlescl** [icindy/wxParse#54]
小程序开发，数据获取从wordpress输出文章内容，因为使用了投稿插件，会自动在文章末尾添加注释
`<!--ap-custom-wrapper-->`

然后小程序里面解析就变成空白，提示nodes未定义（解析失败）。

目前解决办法是解析前去掉上述注释。

**Comment by icindy** [comment]
已经解决这个bug，你可以试一下。

如有错误请贴一些需要解析的代码我试一下
