### ISSUE TITLE
wxParse多数据循环使用时, 数组元素只能是基本数据类型？

### ISSUE THREAD

**Issue by qiubi8801** [icindy/wxParse#56]
如题，数组里的元素只能是基本数据类型吗？ 可不可以是对象或者字典？

**Comment by icindy** [comment]
没太明白你的意思 

数组中不仅是基础类型数据啊 
可以贴一下图 解释一下你的问题

**Comment by qiubi8801** [comment]
我的需求跟#59的需求一样 

list 集合里面有个 description 字段需要解析 html #59

求解决方法

**Comment by icindy** [comment]
请查看wiki使用
[wxParse多数据循环使用方法](https://github.com/icindy/wxParse/wiki/wxParse%E5%A4%9A%E6%95%B0%E6%8D%AE%E5%BE%AA%E7%8E%AF%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
