### ISSUE TITLE
wepy组件化开发时如何使用此插件

### ISSUE THREAD

**Issue by kiner-tang** [icindy/wxParse#57]
目前项目采用了wepy组件化开发框架，不知该如何使用这个插件呢

**Comment by Gcaufy** [comment]
理论上两者不冲突，依然可以import wxParse的JS模块，然后加入wxParse的template。

**Comment by kiner-tang** [comment]
![image](https://cloud.githubusercontent.com/assets/10286961/22005098/b257b40e-dc9b-11e6-8704-cbbaa7570116.png)
他会报找不到模块

**Comment by kiner-tang** [comment]
![image](https://cloud.githubusercontent.com/assets/10286961/22005180/2e73c0dc-dc9c-11e6-8b6c-7dbe1341c1aa.png)
采用import的方式也是一样

**Comment by kiner-tang** [comment]
![image](https://cloud.githubusercontent.com/assets/10286961/22005372/87346784-dc9d-11e6-9b6c-32bd054b2704.png)
![image](https://cloud.githubusercontent.com/assets/10286961/22005377/940fe4ce-dc9d-11e6-89be-9f5c2a96f75e.png)
![image](https://cloud.githubusercontent.com/assets/10286961/22005385/aacf6ac2-dc9d-11e6-802c-2896456d77b7.png)
我修改了一下依赖引入方式就可以了，不知道官方有没有更好的方法

**Comment by Gcaufy** [comment]
刚看了一下，因为wxParse不是使用的相对路径导致编译无法识别。
手动修改`wxParse.js`, `html2json.js`中的`require('xxxx')` 为`require('./xxxx')`即可。

**Comment by kiner-tang** [comment]
恩恩，现在已经可以了，希望更新的时候把这个问题也考虑上，不然下次如果更新新版本还要再手动更改

**Comment by Gcaufy** [comment]
参考这里： https://github.com/icindy/wxParse/pull/58

**Comment by KingJeason** [comment]
// 引入模板
<import src="你的路径/wxParse/wxParse.wxml"/>
//这里data中article为bindName
<template is="wxParse" data="{{wxParseData:article.nodes}}"/>
在wepy中怎么引入模板呢?

**Comment by Blubiubiu** [comment]
https://github.com/Blubiubiu/wxParse 可以看看

**Comment by jacena** [comment]
@kiner-tang @Gcaufy 模板部分该如何引入？

**Comment by jacena** [comment]
@kiner-tang @Gcaufy wepy中模板部分该如何引入？

**Comment by kuailingmin** [comment]
我用了 之后 "/wxparse/wxParse.js" is not defined  在wepy框架中 一直报错，怎么解决？
