### ISSUE TITLE
inline元素单独出来换行了，要怎么优化呢

### ISSUE THREAD

**Issue by Daissmentii** [icindy/wxParse#6]
如下图，strong元素，句号等，应该连贯地显示在一行，如何优化呢
![image](https://img.alicdn.com/imgextra/i2/732450928/TB2k8O6cxaK.eBjSZFAXXczFXXa_!!732450928.png)

**Comment by icindy** [comment]
感觉你是使用的最早版本的了，你可以尝试下载我最新版看下 clone一下，看看是不是还有问题。

同时如果还有问题，请贴一下你的html代码

**Comment by Daissmentii** [comment]
![image](https://img.alicdn.com/imgextra/i4/732450928/TB2a4y8ctuO.eBjSZFCXXXULFXa_!!732450928.png)

**Comment by Daissmentii** [comment]
我是直接运行的你的代码呢

**Comment by icindy** [comment]
好的 看到效果了 我回去后看下。

优化方案的话应该是排除一些行内元素被设置为view，这样就不会换行了
