### ISSUE TITLE
多层嵌套超过11层就没有 显示出来

### ISSUE THREAD

**Issue by kiros1986** [icindy/wxParse#62]
由于历史遗留问题 数据库记录的富文本 太多冗余代码 但是小程序我试了 可以嵌套到20层以上 但是用wxParse只显示到11层 例如

>    <section data-role="outer" label="Powered by 135editor.com">1
    <section data-role="outer" label="Powered by 135editor.com">2
     <section data-role="outer" label="Powered by 135editor.com">3
      <section data-role="outer" label="Powered by 135editor.com">4
       <section data-role="outer" label="Powered by 135editor.com">5
        <section data-role="outer" label="Powered by 135editor.com">6
         <section data-role="outer" label="Powered by 135editor.com">7
          <section data-role="outer" label="Powered by 135editor.com">8
           <section data-role="outer" label="Powered by 135editor.com">9
            <section data-role="outer" label="Powered by 135editor.com">10
             <section data-role="outer" label="Powered by 135editor.com">11
              <section data-role="outer" label="Powered by 135editor.com">12
               <section data-role="outer" label="Powered by 135editor.com">13
                <section data-role="outer" label="Powered by 135editor.com">14
                 <section data-role="outer" label="Powered by 135editor.com">
                    15
                 </section>
                </section>
               </section>
              </section>
             </section>
            </section>
           </section>
          </section>
         </section>
        </section>
       </section>
      </section>
     </section>
    </section>
   </section>

**Comment by kiros1986** [comment]
已经解决了 修改了下wxParse.wxml

**Comment by kiros1986** [comment]
已经解决了 修改了下wxParse.wxml

**Comment by wolfbond007** [comment]
@kiros1986 您好  请问下 您这问题是怎么解决的呢
