### ISSUE TITLE
Template "wxParse12" not found.

### ISSUE THREAD

**Issue by elowes** [icindy/wxParse#66]
Sometimes console will show this warning. I also cannot found the template that name "wxParse12" in wxParse.wxml

**Comment by icindy** [comment]
我英文比较差，你可以使用Google translate下面的话

参见：wiki[https://github.com/icindy/wxParse/wiki/wxParse-%E5%A6%82%E4%BD%95%E9%87%8D%E5%A4%8D%E5%B5%8C%E5%A5%97%E6%A8%A1%E7%89%88](https://github.com/icindy/wxParse/wiki/wxParse-%E5%A6%82%E4%BD%95%E9%87%8D%E5%A4%8D%E5%B5%8C%E5%A5%97%E6%A8%A1%E7%89%88)

**Comment by Gcaufy** [comment]
亮了
