### ISSUE TITLE
实验功能里的a标签功能失效

### ISSUE THREAD

**Issue by Zprestonx** [icindy/wxParse#87]
今天clone了你这个项目，发现在小程序中a标签的功能已经失效了，点击链接后没有反应。我的毕业设计需要用到这个，该怎么解决呢
还有就是使用方法中少了一个步骤，还得在wxml中引入wxParse.wxml“<import src="../../wxParse/wxParse.wxml" />”

**Comment by tanteng** [comment]
微信小程序不支持跳转链接

**Comment by icindy** [comment]
@Zprestonx 这是我的实验室功能，你可以看下源码自己修改一下
最近我没有关注实验室功能

@tanteng 说的对 微信小程序不支持跳转链接
