### ISSUE TITLE
能看为什么不能解析下面的html么

### ISSUE THREAD

**Issue by zhoucheng266** [icindy/wxParse#88]
外联样式感觉无法解析，有什么办法解决了

**Comment by icindy** [comment]
你的外联css是引入到了相应的页面

可以，在开发工具上查看 元素是否挂在了class样式

**Comment by zhoucheng266** [comment]
@icindy  
![default](https://cloud.githubusercontent.com/assets/1034662/24398461/14734794-13dc-11e7-9885-eb474513940f.png)   传过来是这样一段。  用wxparse如何 ，能，明示么

**Comment by icindy** [comment]
目前wxParse不支持 style的css哈
