### ISSUE TITLE
不支持code标签吗？

### ISSUE THREAD

**Issue by JerrySir** [icindy/wxParse#89]
作者试试下面的：
`<p>出结果了，但是还需要各位大神优化<br>1.各个点用一个数组标记，为了方便处理，1-12直接用a,b,c,d,e,f,g,h,i,j,k,l<br>2.对数组内的数据全排列<br>3.根据题意列条件<br>package com.xxu;</p>\n\n<p>public class Problem {<br>\tstatic int n = 0;<br>\tpublic static void main(String[] args) {</p>\n\n<pre><code>    String resource = \"abcdefghijkl\";\n    quanPai(resource);\n    System.out.println(n);\n}\n\npublic static void quanPai(String resource){\n    char[] result = resource.toCharArray(); \n    diGui(result, 0);\n}\nprivate static void diGui(char[] result, int index) {\n    if (index == result.length - 1) {\n    \tif(result[0]-'a'+result[2]-'a'+result[5]-'a'+result[7]-'a'==22)\n    \t\tif(result[0]-'a'+result[3]-'a'+result[6]-'a'+result[10]-'a'==22)\n    \t\t\tif(result[1]-'a'+result[2]-'a'+result[3]-'a'+result[4]-'a'==22)\n    \t\t\t\tif(result[1]-'a'+result[5]-'a'+result[8]-'a'+result[11]-'a'==22)\n    \t\t\t\t\tif(result[7]-'a'+result[8]-'a'+result[9]-'a'+result[10]-'a'==22)\n    \t\t\t\t\t\tif(result[4]-'a'+result[6]-'a'+result[9]-'a'+result[11]-'a'==22)\n    \t\t\t\t\t\t{\n    \t\t\t\t\t\t\tn++;\n    \t\t\t\t\t\t\tSystem.out.printf(\"       %d \",result[0]-'a'+1);\n    \t\t\t\t\t\t\tSystem.out.println();\n    \t\t\t\t\t\t\tSystem.out.printf(\"%d  %d    %d   %d\",result[1]-'a'+1,result[2]-'a'+1,result[3]-'a'+1,result[4]-'a'+1);\n    \t\t\t\t\t\t\tSystem.out.println();\n    \t\t\t\t\t\t\tSystem.out.printf(\"  %d        %d\",result[5]-'a'+1,result[6]-'a'+1);\n    \t\t\t\t\t\t\tSystem.out.println();\n    \t\t\t\t\t\t\tSystem.out.printf(\"%d  %d    %d   %d\",result[7]-'a'+1,result[8]-'a'+1,result[9]-'a'+1,result[10]-'a'+1);\n    \t\t\t\t\t\t\tSystem.out.println();\n    \t\t\t\t\t\t\tSystem.out.printf(\"       %d \",result[11]-'a'+1);\n    \t\t\t\t\t\t\tSystem.out.println();\n    \t\t\t\t\t\t\tSystem.out.println(\"-------------------------------\");\n    \t\t\t\t\t\t}\n\n        \n        return;\n    }\n    diGui(result, index + 1);\n    for (int i = index + 1; i < result.length; i++) {\n        result[index] ^= result[i];\n        result[i] ^= result[index];\n        result[index] ^= result[i];\n        diGui(result, index + 1);\n        result[index] ^= result[i];\n        result[i] ^= result[index];\n        result[index] ^= result[i];\n    }\n}</code></pre>\n\n<p>}</p>`

**Comment by icindy** [comment]
是的 
目前wxParse对code标签的支持不友好

我最近改版wxParse es6
尝试进行友好的改造

谢谢关注

**Comment by JerrySir** [comment]
好的，谢谢作者，还有个问题，我在做discourse的二次开发，里面的emoji好像当成了图片，你再试试下面的解析：
`<p>这个是Java吧？</p>\n\n<aside class=\"quote\" data-post=\"1\" data-topic=\"178\"><div class=\"title\">\n<div class=\"quote-controls\"></div>\n<img alt=\"\" width=\"20\" height=\"20\" src=\"//www.datageekers.com/letter_avatar_proxy/v2/letter/l/3bc359/40.png\" class=\"avatar\">LinkEdu:</div>\n<blockquote><p>result[i] ^= result[index];</p></blockquote></aside>\n\n<p>我从来没用过异或的这种表达式<img src=\"//www.datageekers.com/images/emoji/emoji_one/astonished.png?v=3\" title=\":astonished:\" class=\"emoji\" alt=\":astonished:\"></p>\n\n<p>厉害了，我的哥</p>`

**Comment by JerrySir** [comment]
上面的emoji当成图片，变得超大，我在尝试改你的代码，都尝试一下，还是谢谢作者了

**Comment by icindy** [comment]
你应该是没有引入wxParse.wxss

引入样式就好了

**Comment by JerrySir** [comment]
您试一下下面这段：
`<p>厉害了word哥<img src=\"//www.datageekers.com/images/emoji/emoji_one/grin.png?v=3\" title=\":grin:\" class=\"emoji\" alt=\":grin:\">。我补充一下，原题目往下看：<br><div class=\"lightbox-wrapper\"><a data-download-href=\"//www.datageekers.com/uploads/default/e9629697d060d7a725c585f8cc8983714ea30ad1\" href=\"//www.datageekers.com/uploads/default/original/1X/e9629697d060d7a725c585f8cc8983714ea30ad1.jpg\" class=\"lightbox\" title=\"410142854135059005.jpg\"><img src=\"//www.datageekers.com/uploads/default/optimized/1X/e9629697d060d7a725c585f8cc8983714ea30ad1_1_375x500.jpg\" width=\"375\" height=\"500\"><div class=\"meta\">\n<span class=\"filename\">410142854135059005.jpg</span><span class=\"informations\">960x1280 82 KB</span><span class=\"expand\"></span>\n</div></a></div></p>`
放到非循环的解析里面就正常，但是放到循环里面当做评论，就会出现图片非常大的那样，您试一下

**Comment by JerrySir** [comment]
请问一下，这个问题解决了吗？

**Comment by dwqs** [comment]
pre 标签是小程序不支持，要解析 code  可以试试 [mpvue-markdown-parser](https://github.com/dwqs/mpvue-markdown-parser)
